apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-ubuntu
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: zowe-apache
  type: NodePort
status:
  loadBalancer: {}
